# Transformers and Attention-Based Deep Networks Assignment - 1

Made by Khudiakova Kseniia, e278979

## Setup

and connection to wandb

In [4]:
!pip install transformers wandb seaborn matplotlib pandas -q

In [6]:
import pandas as pd

In [15]:
import wandb

# wandb.login(key="")

In [2]:
wandb.init(
    project="odtu-transformer-assignment",
    name="baseline-setup",
    config={
        "model": "distilbert-base-uncased",
        "batch_size": 16,
        "lr": 2e-5,
        "epochs": 3
    }
)

## Import data

In [7]:
train_path = "/kaggle/input/datasets/khudiakovakseniia/transformers-ass1/train.csv"
test_path  = "/kaggle/input/datasets/khudiakovakseniia/transformers-ass1/test.csv"

train_df = pd.read_csv(train_path)
test_df  = pd.read_csv(test_path)

In [13]:
print("Train dataset sample:")
display(train_df.head())

train_df.describe()

Train dataset sample:

,issue_area,issue_category,issue_sub_category,issue_category_sub_category,customer_sentiment,product_category,product_sub_category,issue_complexity,agent_experience_level,agent_experience_level_desc,conversation
0,Login and Account,Mobile Number and Email Verification,Verification requirement for mobile number or ...,Mobile Number and Email Verification -> Verifi...,neutral,Appliances,Oven Toaster Grills (OTG),medium,junior,"handles customer inquiries independently, poss...",Agent: Thank you for calling BrownBox Customer...
1,Cancellations and returns,Pickup and Shipping,Reasons for being asked to ship the item,Pickup and Shipping -> Reasons for being asked...,neutral,Electronics,Computer Monitor,less,junior,"handles customer inquiries independently, poss...",Agent: Thank you for calling BrownBox customer...
2,Cancellations and returns,Replacement and Return Process,Inability to click the 'Cancel' button,Replacement and Return Process -> Inability to...,neutral,Appliances,Juicer/Mixer/Grinder,medium,experienced,"confidently handles complex customer issues, e...",Agent: Thank you for calling BrownBox Customer...
3,Login and Account,Login Issues and Error Messages,Error message regarding exceeded attempts to e...,Login Issues and Error Messages -> Error messa...,neutral,Appliances,Water Purifier,less,inexperienced,"may struggle with ambiguous queries, rely on c...","Customer: Hi, I am facing an issue while loggi..."
4,Order,Order Delivery Issues,Delivery not attempted again,Order Delivery Issues -> Delivery not attempte...,negative,Electronics,Bp Monitor,medium,experienced,"confidently handles complex customer issues, e...",Agent: Thank you for contacting BrownBox custo...

,issue_area,issue_category,issue_sub_category,issue_category_sub_category,customer_sentiment,product_category,product_sub_category,issue_complexity,agent_experience_level,agent_experience_level_desc,conversation
count,970,970,970,970,970,970,970,970,970,970,970
unique,6,40,109,109,3,3,50,3,3,3,968
top,Cancellations and returns,Return and Exchange,Verification requirement for mobile number or ...,Mobile Number and Email Verification -> Verifi...,neutral,Appliances,Bp Monitor,less,junior,"handles customer inquiries independently, poss...","Agent: You're welcome, Jane. Have a great day!"
freq,277,92,17,17,542,454,26,472,490,490,3

In [14]:
print("test dataset sample:")
display(test_df.head())

test_df.describe()

test dataset sample:

,issue_area,issue_category,issue_sub_category,issue_category_sub_category,customer_sentiment,product_category,product_sub_category,issue_complexity,agent_experience_level,agent_experience_level_desc,conversation
0,Shopping,Pricing and Discounts,Discounts through exchange offers,Pricing and Discounts -> Discounts through exc...,negative,Appliances,Hand Blender,less,experienced,"confidently handles complex customer issues, e...",Agent: Thank you for calling BrownBox Customer...
1,Login and Account,Account Reactivation and Deactivation,Reactivating an inactive account,Account Reactivation and Deactivation -> React...,negative,Men/Women/Kids,Wrist Watch,medium,junior,"handles customer inquiries independently, poss...",Agent: Thank you for calling BrownBox Customer...
2,Cancellations and returns,Cash on Delivery (CoD) Refunds,Refund timelines for Cash on Delivery returns,Cash on Delivery (CoD) Refunds -> Refund timel...,negative,Appliances,Induction Cooktop,less,junior,"handles customer inquiries independently, poss...",Agent: Thank you for calling BrownBox Customer...
3,Order,Order Delivery Issues,Package shows as delivered but cannot be found,Order Delivery Issues -> Package shows as deli...,negative,Men/Women/Kids,Sunglas,high,junior,"handles customer inquiries independently, poss...",Agent: Thank you for calling BrownBox Customer...
4,Cancellations and returns,Pickup and Shipping,Reimbursement of courier charges for return,Pickup and Shipping -> Reimbursement of courie...,negative,Electronics,Computer Monitor,medium,experienced,"confidently handles complex customer issues, e...",Agent: Thank you for calling BrownBox Customer...

,issue_area,issue_category,issue_sub_category,issue_category_sub_category,customer_sentiment,product_category,product_sub_category,issue_complexity,agent_experience_level,agent_experience_level_desc,conversation
count,30,30,30,30,30,30,30,30,30,30,30
unique,6,16,22,22,3,3,21,3,3,3,30
top,Order,Order Confirmation and Status,Confirming order status,Order Confirmation and Status -> Confirming or...,negative,Appliances,Vacuum Cleaner,less,junior,"handles customer inquiries independently, poss...",Agent: Thank you for calling BrownBox Customer...
freq,12,6,5,5,10,11,3,16,17,17,1

## Exploratory Data Analysis

## Preprocessing

## Model

## Training

## Test

## Save & conclusion